Repository lando/lando, pull requests merged in 2018-03, with the labels that each got.

#708 Add turn off Docker
  docs/installation/updating.md
Labels: documentation

#702 Document lamp appserver `via` option on recipe tut
  examples/lamp2/.lando.yml
Labels: documentation

#734 Closes #647 - Allow Remote Docker
  bin/lando.js
  docs/changelog/2018.md
  docs/config/config.md
  lib/config.js
  plugins/lando-engine/lib/env.js
  test/config.spec.js
Labels: dx, feature

#712 Closes #675
  .circleci/config.yml
  .travis.yml
  docs/api/api.md
  docs/changelog/2018.md
  docs/contrib/contributing.md
  docs/dev/testing.md
  lib/config.js
  package.json
  plugins/lando-app/tasks/list.js
  plugins/lando-app/test/.eslintrc.json
  plugins/lando-app/test/functional/cli/app.spec.js
  plugins/lando-core/test/.eslintrc.json
  plugins/lando-core/test/functional/cli/basic-usage.spec.js
  plugins/lando-init/test/functional/cli/init.spec.js
  plugins/lando-tooling/test/functional/cli/tooling.spec.js
  test/unit/cache.spec.js
  test/unit/config.spec.js
  test/unit/events.spec.js
  yarn.lock
Labels: ready

#600 Documentation on integrating lando docker setup with IDE like PHPStorm to run stuff like PHPUnit
  docs/images/add-remote-interpreter-docker.png
  docs/images/test-frameworks-remote-interperter.png
  docs/tutorials/drupal8.md
Labels: RTBC, documentation

#824 396 windows file uploads
  docs/SUMMARY.md
  docs/changelog/2018.md
  docs/issues/drupal-win-upload.md
  docs/issues/win-file-upload.md
  plugins/lando-services/services/php/php.js
  plugins/lando-services/services/php/zz-lando.conf
Labels: bug
